### PR TITLE
[SWA-42][FEAT] - Add BiSwap as routable DEX for BNB chain

### PR DESCRIPTION
**Pull request by ElRodrigote**
## Fixes: [SWA-42](https://linear.app/swaprdev/issue/SWA-42/add-biswap-to-bsc)

# Description

* Add BiSwap as routable DEX for BNB chain
* Update repo docs for routable platforms and supported chains
* Add new docs section explaining how to add a new dex if it's a UniV2 fork

### CODE REVIEW

**Comment by ElRodrigote** [comment]
@NelsonGaldeman all the auto-generated code most like would be from the `dist` folder added in [this commit](https://github.com/SwaprHQ/swapr-sdk/pull/310/commits/afca05282582d45ccbe2666b7916c97afca82f33)

Leo told me to add this folder for testing purposes, so we can tag this remote branch (like I do [here](https://github.com/SwaprHQ/swapr-dapp/pull/1831/commits/1d8c9232b3b6b6d97f36e0aca19acd163b779a78) ) from the dapp `package.json` file and test it locally

**Comment by NelsonGaldeman** [comment]
What I'm saying is we shouldn't have auto-generated code on github (except maybe for ABIs). Instead, we should have built-in commands to generate them during package installation. Pretty much same reason why we don't push `node_modules`. I'm not a FE expert so I'm not sure how this files are generated or what are being used for, just commeting on general good development practices. If there is a very specific reason to have them on the repo fine, but if there is not, they shouldn't be there.

On the SDK version, it's fine for local testing purposes, but not for a PR that will be merged into a production release. Reviewers should change this locally for testing purposes, if needed.

**Comment by berteotti** [comment]
@NelsonGaldeman I suggested Rorry to do this, so we can easily test the changes on dapp PRs (eg. testers and Venky can test it without running it locally). One other solution is to create a PR for the changes and have another branch with the current changes + dist folder for the preview. Other solution is to declare this PR as a draft as it's not merge ready. What do you think? @ElRodrigote @NelsonGaldeman

**Review by berteotti — APPROVED** [review]
Awesome, this looks good!

**Pull request merged**
